default_stages: [commit]
default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [
          --fix, 
          --ignore=E402,
          --line-length=79, 
        ]

      # Run the formatter.
      - id: ruff-format
        args: [
          --line-length=79
      ]
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        verbose: True
        args:
          - -vv
          - --fail-under=50    

